### ISSUE TITLE
Native: All alerts key not closing on back

### ISSUE THREAD

**Issue by philj56** [scooper93/Chirp#20] opened 2020-01-14 13:29 UTC
The "Likely Type" key popup on the all alerts page doesn't close when pressing the back button on Android.

**Comment by scooper93** [comment] 2020-01-14 13:58
What phone @philj56 ? I've tried it (admittedly on a development build) and cannot reproduce.

**Comment by philj56** [comment] 2020-01-14 14:31
Pixel 2 on Android 10

**Comment by scooper93** [comment] 2020-01-14 15:08
Just leaving a note to myself that this doesn't show up on the development build as the settings icon is in the way.

**Comment by scooper93** [comment] 2020-02-19 01:11
This has been fixed in the latest commit

**Closed as completed by scooper93** 2020-02-19 01:11 UTC
